### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by muddlebee** [pdtaylor/PCDoctorExpert#2]
Does it work for Apache 2.x or PHP 5.0 + or MySql 5.0 + versions ?
The homepage doesn't render properly upon opening

**Comment by pdtaylor** [comment]
Are you using the bundled WAMP/LAMP/MAMP distributions or are you installing them independently?

**Comment by muddlebee** [comment]
OS : Ubuntu 14.04 LTS
I installed it independently. 

It throws dozens of error finally got it up somehow changing a few lines of code. You should add some instructions for Linux too.

**Comment by pdtaylor** [comment]
So please remember that this project was developed some time ago as an example of how you would go about using the PHP-CLIPS technology. The technology used to create this project is pretty dated (e.g. Apache 1.3, PHP 5.1, MySQL 5.1) and so much of the PHP code constructs are deprecated. Therefore there will be a few issues with running this with the latest Apache, PHP, and MySQL. There are just a few tweaks you will need to make:
- Remove all the references to the database engine being applied on the tables (e.g. InnoDB, MYISAM, etc.) in the SQL file. 
- Change all the mysql php functions to the mysqli standard.

I will make the changes to the codebase in the near future, but in the meantime, I would recommend that you make those changes yourself, or simply use the installation files provided in the repository. 

Thanks for the tip as well. I will add the instructions for Linux.
